stages:
- name: build & publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: anof/dockerdjango
      pushRemote: true
      registry: index.docker.io
timeout: 60
notification: {}
